FROM golang:1.22-alpine AS firstStage

WORKDIR /govservice/
COPY ./ ./

WORKDIR /govservice/admin-api-gateway
RUN apk --no-cache add git ca-certificates
RUN go mod download
RUN go build -o ./cmd/binary ./cmd/main.go

FROM scratch
COPY --from=firstStage /govservice/admin-api-gateway/cmd/binary /
COPY --from=firstStage /govservice/admin-api-gateway/internal/config/config.env /internal/config/config.env
COPY --from=firstStage /govservice/admin-api-gateway/internal/config/public.key /internal/config/public.key
COPY --from=firstStage /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
EXPOSE 4001
CMD [ "/binary" ]